using System;
using System.Collections.Generic;

namespace ResourceRequestService.Models.EMPDATA
{
    public partial class ExIpperson
    {
        public string PeLogn { get; set; }
        public string EmergencyContact { get; set; }
        public string Pc { get; set; }
        public string Configuration { get; set; }
        public string Internet { get; set; }
        public string BandWidth { get; set; }
        public string UserLognId { get; set; }
        public DateTime? EntryStamp { get; set; }
        public string Status { get; set; }
        public string FunctMngrLogn { get; set; }
        public string VisaValidity { get; set; }
        public string PoliceVeriDetail { get; set; }
        public DateTime? PoliceVeriDt { get; set; }
        public DateTime? PoliceVeriFromDt { get; set; }
        public DateTime? PoliceVeriToDt { get; set; }
        public string PoliceVeriRefNo { get; set; }
        public string BirthPlace { get; set; }
        public string BloodGroup { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public DateTime? SpouseDob { get; set; }
        public DateTime? MarriageDate { get; set; }
        public int? NoOfChilds { get; set; }
        public int? NoOfDependents { get; set; }
        public string PersonalEmail1 { get; set; }
        public string PersonalEmail2 { get; set; }
        public string Hobbies { get; set; }
        public string Sports { get; set; }
        public string Pan { get; set; }
        public DateTime? PassportIssueDt { get; set; }
        public string PassportIssuePlace { get; set; }
        public string Ecnr { get; set; }
        public string BankAc { get; set; }
        public string BankActype { get; set; }
        public string BankName { get; set; }
        public string NiNumber { get; set; }
        public DateTime? BgvIniDt { get; set; }
        public string BgvStatus { get; set; }
        public string BgvComments { get; set; }
        public string NortelExtnNo { get; set; }
        public string EduBackVeri { get; set; }
        public string PrvEmpBackVeri { get; set; }
        public string CriminalBackVeri { get; set; }
        public string CriminalDatabaseCheck { get; set; }
        public string ExtnNo { get; set; }
        public int? EmploymentType { get; set; }
        public int? WorkType { get; set; }
        public int? Hrisid { get; set; }
        public int? LandMarkId { get; set; }
        public string Confirmed { get; set; }
        public DateTime? ConfirmationDate { get; set; }
        public string ConfirmedBy { get; set; }
        public DateTime? ConfirmedEntryStamp { get; set; }
        public string ConfirmedStatus { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovedEntryStamp { get; set; }
        public string Comments { get; set; }
        public string PaymentMode { get; set; }
        public string IsPfapplicable { get; set; }
        public string Pfnumber { get; set; }
        public string IsEsiapplicable { get; set; }
        public string Esinumber { get; set; }
        public string Esidespensary { get; set; }
        public DateTime? ResignationDate { get; set; }
        public DateTime? LastWorkingDate { get; set; }
        public string Reason { get; set; }
        public string PersonalMailId { get; set; }
        public string Isbillable { get; set; }
        public DateTime? QuitDateTemp { get; set; }
        public DateTime? ResignationDateTemp { get; set; }
        public DateTime? LastWorkingDateTemp { get; set; }
        public int? ReasonTemp { get; set; }
        public DateTime? EntryStampTemp { get; set; }
        public string StatusTemp { get; set; }
        public string UpdatedByTemp { get; set; }
        public string PassportName { get; set; }
        public string OldMailId { get; set; }
        public string DrugTestStatus { get; set; }
        public string EmergencyLandLine { get; set; }
        public string EmergencyMobile { get; set; }
        public string PerEmail { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? AdDeactivatedDate { get; set; }
        public string CopalEmailId { get; set; }
        public string ConfirmedAcknowledgedBy { get; set; }
        public DateTime? ConfirmedAcknowledgedOn { get; set; }
        public string AlertFindUpdatedBy { get; set; }
        public DateTime? AlertFindUpdatedOn { get; set; }
        public string AlertFindStatus { get; set; }
        public string AadharCardNo { get; set; }
        public string AadharCardName { get; set; }
        public DateTime? AadharCardDob { get; set; }
        public string AadharCardGender { get; set; }
        public string AadharCardFatherName { get; set; }
        public string Uan { get; set; }
        public string ServiceLine { get; set; }
        public string TshirtSize { get; set; }
        public string WwPersonId { get; set; }
        public string IsFirstCompany { get; set; }
        public int? SourceHiringId { get; set; }
        public DateTime? IdbcompletionDate { get; set; }
        public DateTime? IdentityCheckCompletionDate { get; set; }
        public DateTime? BgvclosureDate { get; set; }
        public DateTime? DrugTestCompletionDate { get; set; }
        public int? BgvVendorId { get; set; }
        public string NationalId { get; set; }
        public int? Hukouid { get; set; }
        public int? ReasonType { get; set; }
        public int? EmergencyContactRelationId { get; set; }
        public int? PrimaryCitizenShip { get; set; }
        public DateTime? LatestHireDate { get; set; }
        public string IsReHire { get; set; }
        public DateTime? LatestEmploymentChangeDate { get; set; }
        public string ExitReasonDesc { get; set; }
        public string PmsfinalRating { get; set; }
        public string IsEmpRetain { get; set; }

        public DateTime? GroupDOJ { get; set; } 
        public int? PersonType { get; set; }
    }
}
